#![doc = include_str!("../README.md")]

use sqlparser::{ast::Statement, parser::Parser};

#[derive(Default)]
struct Formatter {
    options: FormatterOptions,
    generator: CodeGenerator,
    current_context: FormatContext,
}

impl Formatter {
    fn push_statement(&mut self, stmt: Statement) {
        self.generator.generate_statement(stmt);
    }

    /// Get `String` of generated source code.
    fn into_code(self) -> String {
        self.generator.generate_code()
    }
}

/// `CodeGenerator` is used to generate source code from SQL statements.
#[derive(Default)]
struct CodeGenerator {
    bytes: Vec<u8>,
}

impl CodeGenerator {
    /// Generate code from a `sqlparser::parser::Statement`.
    fn generate_statement(&mut self, stmt: Statement) {
        self.push_statement_bytes(stmt);
    }

    /// Pushes generated bytes for `sqlparser::parser::Statement`.
    fn push_statement_bytes(&mut self, stmt: Statement) {
        todo!()
    }

    /// Move into a `String` of the current generated code.
    fn generate_code(self) -> String {
        unsafe { String::from_utf8_unchecked(self.bytes) }
    }
}

struct FormatterOptions {
    line_length: usize,
    indentation_kind: IntentationKind,
}

impl Default for FormatterOptions {
    fn default() -> Self {
        Self {
            line_length: 88,
            indentation_kind: IntentationKind::Indent,
        }
    }
}

#[derive(Default)]
struct FormatContext {
    needs_semicolon: bool,
    current_indentation: u8,
}

enum IntentationKind {
    Indent,
    Space,
}

pub fn format(s: &str) -> String {
    let statements = match Parser::new(&sqlparser::dialect::MsSqlDialect {}).try_with_sql(s) {
        Ok(mut parser) => parser.parse_statements().expect("parse sql statements"),
        Err(_) => panic!("failed to parse sql ast"),
    };

    format_statements(statements, FormatterOptions::default())
}

fn format_statements(statements: Vec<Statement>, formatter_options: FormatterOptions) -> String {
    let mut formatter = Formatter {
        options: formatter_options,
        generator: CodeGenerator { bytes: Vec::new() },
        current_context: FormatContext::default(),
    };

    statements
        .into_iter()
        .for_each(|stmt| formatter.push_statement(stmt));

    formatter.into_code()
}
